/*
 * Copyright (c) IntellectualCrafters - 2014. You are not allowed to distribute
 * and/or monetize any of our intellectual property. IntellectualCrafters is not
 * affiliated with Mojang AB. Minecraft is a trademark of Mojang AB.
 *
 * >> File = Claim.java >> Generated by: Citymonstret at 2014-08-09 01:41
 */

package com.intellectualcrafters.plot.commands;

import java.lang.reflect.Field;

import org.bukkit.entity.Player;

import com.intellectualcrafters.plot.PlayerFunctions;
import com.intellectualcrafters.plot.PlotMain;
import com.intellectualcrafters.plot.database.DBFunc;

/**
 * @author Citymonstret
 */
public class DebugLoadTest extends SubCommand {

    public DebugLoadTest() {
        super(Command.DEBUGCLAIMTEST, "This debug command will force the reload of all plots in the DB", "claim", CommandCategory.DEBUG, false);
    }

    @Override
    public boolean execute(final Player plr, final String... args) {
        if (plr == null) {
            try {
                final Field fPlots = PlotMain.class.getDeclaredField("plots");
                fPlots.setAccessible(true);
                fPlots.set(null, DBFunc.getPlots());
            }
            catch (final Exception e) {
                PlotMain.sendConsoleSenderMessage("&3===FAILED&3===");
                e.printStackTrace();
                PlotMain.sendConsoleSenderMessage("&3===END OF STACKTRACE===");
            }
        }
        else {
            PlayerFunctions.sendMessage(plr, "This debug command can only be executed by console as it has been deemed unsafe if abused.");
        }
        return true;
    }
}
