/*
 * Copyright (c) IntellectualCrafters - 2014.
 * You are not allowed to distribute and/or monetize any of our intellectual property.
 * IntellectualCrafters is not affiliated with Mojang AB. Minecraft is a trademark of Mojang AB.
 *
 * >> File = Help.java
 * >> Generated by: Citymonstret at 2014-08-11 17:32
 */

package com.intellectualcrafters.plot.commands;

import org.bukkit.entity.Player;

/**
 * Created by Citymonstret on 2014-08-11.
 */
public class Help extends SubCommand {
    public Help() {
        super("help", "", "Get this help menu", "help", "he", SubCommand.CommandCategory.INFO);
    }
    public boolean execute(Player plr, String ... args) { return false; }
}
