/*
 * Copyright (c) IntellectualCrafters - 2014.
 * You are not allowed to distribute and/or monetize any of our intellectual property.
 * IntellectualCrafters is not affiliated with Mojang AB. Minecraft is a trademark of Mojang AB.
 *
 * >> File = plugin.java
 * >> Generated by: Citymonstret at 2014-08-09 01:42
 */

package com.intellectualcrafters.plot.commands;

import java.util.ArrayList;

import org.bukkit.entity.Player;

import com.intellectualcrafters.plot.PlayerFunctions;
import com.intellectualcrafters.plot.PlotMain;
import com.intellectualcrafters.plot.Settings;

public class plugin extends SubCommand {

    public plugin() {
        super("plugin", "", "Show plugin information", "plugin", "pl", CommandCategory.INFO);
    }

    @Override
    public boolean execute(Player plr, String... args) {
        ArrayList<String> strings = new ArrayList<String>() {
            {
                add(String.format("&c>> &6PlotSquared (Version: %s)", PlotMain.getMain().getDescription().getVersion()));
                add(String.format("&c>> &6Made by Citymonstret and brandonrelph"));
                add(String.format("&c>> &6Download at %s", Settings.URL));
            }
        };
        for (String s : strings) {
            PlayerFunctions.sendMessage(plr, s);
        }
        return true;
    }

}
