/*
 * Copyright (c) IntellectualCrafters - 2014. You are not allowed to distribute
 * and/or monetize any of our intellectual property. IntellectualCrafters is not
 * affiliated with Mojang AB. Minecraft is a trademark of Mojang AB.
 * 
 * >> File = Purge.java >> Generated by: Citymonstret at 2014-08-09 01:42
 */

package com.intellectualcrafters.plot.commands;

import org.bukkit.entity.Player;

import com.intellectualcrafters.plot.C;
import com.intellectualcrafters.plot.PlayerFunctions;
import com.intellectualcrafters.plot.PlotMain;
import com.intellectualcrafters.plot.PlotWorld;
import com.intellectualcrafters.plot.database.DBFunc;

/**
 * @Deprecated
 */
public class Purge extends SubCommand {

	public Purge() {
		super("purge", "plots.admin", "Purge all plots for a world", "purge", "", CommandCategory.ACTIONS, false);
	}

	@Override
	public boolean execute(Player plr, String... args) {
		if (args.length!=1) {
			PlayerFunctions.sendMessage(plr, C.PURGE_SYNTAX);
			return false;
		}
		PlotWorld plotworld = PlotMain.getWorldSettings(args[0]);
		if (plotworld == null) {
			PlayerFunctions.sendMessage(plr, C.NOT_VALID_PLOT_WORLD);
			return false;
		}
		if (plr!=null) {
			PlayerFunctions.sendMessage(plr, (C.NOT_CONSOLE));
			return false;
		}
		DBFunc.purge(args[0]);
		PlayerFunctions.sendMessage(plr, (C.PURGE_SUCCESS));
		return true;
	}

}
