name: Announce release on discord
on:
  release:
    types: [ published ]
jobs:
  send_announcement:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: PlotSquared Release
          DISCORD_AVATAR: https://raw.githubusercontent.com/IntellectualSites/Assets/main/plugins/PlotSquared/PlotSquared.png
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: |
            "<@&525015541815967744> <@&679322738552471574> <@&699293353862496266>"
            ""
            "<:plotsquared:730750385886593039> **PlotSquared ${{ github.event.release.tag_name }} has been released!**"
            ""
            "Click here to view changelog: https://github.com/IntellectualSites/PlotSquared/releases/tag/${{ github.event.release.tag_name }}"
            ""
            "The download is available at:"
            "- Spigot: <https://www.spigotmc.org/resources/77506/>"
